{
 "title": "API Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Estado de criticidad actual",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "criticity_updates",
     "query": "SELECT last(\"criticity_value\") FROM \"criticity_updates\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "criticity_value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cantidad de consultas de estado",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "app_name::tag" ], "type": "tag" }
     ],
     "measurement": "requests",
     "query": "SELECT sum(\"cantidad\") FROM \"requests\" WHERE $timeFilter GROUP BY time($__interval), \"app_name\"::tag fill(0)",
     "select": [
      [
       { "params": [ "cantidad" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Evaluación del estado de criticidad",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "criticity_updates",
     "select": [
      [
       { "params": [ "criticity_value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}