version: "3.8"
services:

  app_desafio_1:
    image: agustinnormand/app_desafio_1:0.7
    container_name: app_desafio_1
    ports:
      - "8000:8000"
    environment:
      - APIKEY=${FAST_API_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET_CONSUMERS=${INFLUXDB_BUCKET_CONSUMERS}
      - INFLUXDB_BUCKET_PRODUCERS=${INFLUXDB_BUCKET_PRODUCERS}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
      - INFLUXDB_URL=http://influxdb:8086
    networks:
      - default

  consumer_50_desafio_1:
    image: agustinnormand/consumer_desafio_1:0.5
    container_name: consumer_50_desafio_1
    environment:
      - APIKEY=${FAST_API_TOKEN}
      - API_URL=http://app_desafio_1:8000/secapp/update
      - APPNAME=secapp50
    networks:
      - default

  consumer_100_desafio_1:
    image: agustinnormand/consumer_desafio_1:0.5
    container_name: consumer_100_desafio_1
    environment:
      - APIKEY=${FAST_API_TOKEN}
      - API_URL=http://app_desafio_1:8000/secapp/update
      - APPNAME=secapp100
    networks:
      - default

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_USER_PASSWORD}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_USER_PASSWORD}
    networks:
      - default
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb/config:/etc/influxdb2
      - ./influxdb/db:/var/lib/influxdb2

  grafana:
    image: grafana/grafana-enterprise:latest
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
    volumes:
      - ./grafana/data/:/var/lib/grafana
    depends_on:
      - influxdb
    environment:
      - "GF_SECURITY_ADMIN_USER=${GRAFANA_USER}"
      - "GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_USER_PASSWORD}"
    user: "0"

  app_desafio_2:
    image: agustinnormand/app_desafio_2:0.10
    container_name: app_desafio_2
    environment:
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
      - INFLUXDB_URL=http://influxdb:8086
      - DATA_FILENAME=Datos_uptime_challenge.tsv
    networks:
      - default
    depends_on:
      - influxdb