{
 "title": "Downtime Dashboard",
 "time": { "from": "2019-01-01T03:00:00.000Z", "to": "2024-01-01T02:59:59.000Z" },
 "panels": [
  { "title": "Uptime Generales", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Valores de Uptime - Todas las apps",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downtimes",
     "query": "SELECT (100 - (sum(\"miliseconds_downtime\") / ($__interval_ms * 5)) * 100) AS uptime_percentage\nFROM \"downtimes\"\nWHERE  $timeFilter\nGROUP BY time($__interval), \"app_name\"::tag fill(100)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Línea de tiempo de Uptime - General",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "SELECT (100 - (sum(\"miliseconds_downtime\") / ($__interval_ms * 5)) * 100) AS uptime_percentage\nFROM \"downtimes\"\nWHERE $timeFilter\nGROUP BY time($__interval) fill(100)"
    }
   ]
  },
  {
   "title": "Valor de Uptime - General",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "SELECT (100 - (sum(\"miliseconds_downtime\") / ($__interval_ms * 5)) * 100) AS uptime_percentage\nFROM \"downtimes\"\nWHERE  $timeFilter\nGROUP BY time($__interval) fill(100)"
    }
   ]
  },
  { "title": "Uptime Por Aplicación", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Línea de tiempo de Uptime - App1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "SELECT (100 - (sum(\"miliseconds_downtime\") / $__interval_ms) * 100) AS uptime_percentage\nFROM \"downtimes\"\nWHERE (\"app_name\"::tag = 'app1') AND $timeFilter\nGROUP BY time($__interval) fill(100)"
    }
   ]
  },
  {
   "title": "Valor de Uptime - App1",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "SELECT (100 - (sum(\"miliseconds_downtime\") / $__interval_ms) * 100) AS uptime_percentage\nFROM \"downtimes\"\nWHERE (\"app_name\"::tag = 'app1') AND $timeFilter\nGROUP BY time($__interval) fill(100)"
    }
   ]
  },
  {
   "title": "Línea de tiempo de Uptime - App2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "query": "SELECT (100 - (sum(\"miliseconds_downtime\") / $__interval_ms) * 100) AS uptime_percentage\nFROM \"downtimes\"\nWHERE (\"app_name\"::tag = 'app2') AND $timeFilter\nGROUP BY time($__interval) fill(100)"
    }
   ]
  },
  {
   "title": "Valor de Uptime - App2",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "SELECT (100 - (sum(\"miliseconds_downtime\") / $__interval_ms) * 100) AS uptime_percentage\nFROM \"downtimes\"\nWHERE (\"app_name\"::tag = 'app2') AND $timeFilter\nGROUP BY time($__interval) fill(100)"
    }
   ]
  },
  {
   "title": "Línea de tiempo de Uptime - App3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "query": "SELECT (100 - (sum(\"miliseconds_downtime\") / $__interval_ms) * 100) AS uptime_percentage\nFROM \"downtimes\"\nWHERE (\"app_name\"::tag = 'app3') AND $timeFilter\nGROUP BY time($__interval) fill(100)"
    }
   ]
  },
  {
   "title": "Valor de Uptime - App3",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "SELECT (100 - (sum(\"miliseconds_downtime\") / $__interval_ms) * 100) AS uptime_percentage\nFROM \"downtimes\"\nWHERE (\"app_name\"::tag = 'app3') AND $timeFilter\nGROUP BY time($__interval) fill(100)"
    }
   ]
  },
  {
   "title": "Línea de tiempo de Uptime - App4",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (100 - (sum(\"miliseconds_downtime\") / $__interval_ms) * 100) AS uptime_percentage\nFROM \"downtimes\"\nWHERE (\"app_name\"::tag = 'app4') AND $timeFilter\nGROUP BY time($__interval) fill(100)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Valor de Uptime - App4",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "SELECT (100 - (sum(\"miliseconds_downtime\") / $__interval_ms) * 100) AS uptime_percentage\nFROM \"downtimes\"\nWHERE (\"app_name\"::tag = 'app4') AND $timeFilter\nGROUP BY time($__interval) fill(100)"
    }
   ]
  },
  {
   "title": "Línea de tiempo de Uptime - App5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "query": "SELECT (100 - (sum(\"miliseconds_downtime\") / $__interval_ms) * 100) AS uptime_percentage\nFROM \"downtimes\"\nWHERE (\"app_name\"::tag = 'app5') AND $timeFilter\nGROUP BY time($__interval) fill(100)"
    }
   ]
  },
  {
   "title": "Valor de Uptime - App5",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "SELECT (100 - (sum(\"miliseconds_downtime\") / $__interval_ms) * 100) AS uptime_percentage\nFROM \"downtimes\"\nWHERE (\"app_name\"::tag = 'app5') AND $timeFilter\nGROUP BY time($__interval) fill(100)"
    }
   ]
  },
  { "title": "Uptime vinculando Aplicaciones", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Valores de Uptime - App1 y el resto",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "app1 y app2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (100 - (sum(\"miliseconds_downtime\") / ($__interval_ms * 2)) * 100) \nFROM \"downtimes\"\nWHERE (\"app_name\"::tag = 'app1') OR (\"app_name\"::tag = 'app2') AND $timeFilter\nGROUP BY time($__interval) fill(100)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "app1 y app3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (100 - (sum(\"miliseconds_downtime\") / ($__interval_ms * 2)) * 100) AS uptime_percentage\nFROM \"downtimes\"\nWHERE (\"app_name\"::tag = 'app1') OR (\"app_name\"::tag = 'app3') AND $timeFilter\nGROUP BY time($__interval) fill(100)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "app1 y app4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (100 - (sum(\"miliseconds_downtime\") / ($__interval_ms * 2)) * 100) AS uptime_percentage\nFROM \"downtimes\"\nWHERE (\"app_name\"::tag = 'app1') OR (\"app_name\"::tag = 'app4') AND $timeFilter\nGROUP BY time($__interval) fill(100)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "app1 y app5",
     "query": "SELECT (100 - (sum(\"miliseconds_downtime\") / ($__interval_ms * 2)) * 100) AS uptime_percentage\nFROM \"downtimes\"\nWHERE (\"app_name\"::tag = 'app1') OR (\"app_name\"::tag = 'app5') AND $timeFilter\nGROUP BY time($__interval) fill(100)"
    }
   ]
  },
  {
   "title": "Valores de Uptime - App2 y el resto",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "app2 y app3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (100 - (sum(\"miliseconds_downtime\") / ($__interval_ms * 2)) * 100) AS uptime_percentage\nFROM \"downtimes\"\nWHERE (\"app_name\"::tag = 'app2') OR (\"app_name\"::tag = 'app3') AND $timeFilter\nGROUP BY time($__interval) fill(100)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "app2 y app4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (100 - (sum(\"miliseconds_downtime\") / ($__interval_ms * 2)) * 100) AS uptime_percentage\nFROM \"downtimes\"\nWHERE (\"app_name\"::tag = 'app2') OR (\"app_name\"::tag = 'app4') AND $timeFilter\nGROUP BY time($__interval) fill(100)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "app2 y app5",
     "query": "SELECT (100 - (sum(\"miliseconds_downtime\") / ($__interval_ms * 2)) * 100) AS uptime_percentage\nFROM \"downtimes\"\nWHERE (\"app_name\"::tag = 'app2') OR (\"app_name\"::tag = 'app5') AND $timeFilter\nGROUP BY time($__interval) fill(100)"
    }
   ]
  },
  {
   "title": "Valores de Uptime - App3 y el resto",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "app3 y app4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (100 - (sum(\"miliseconds_downtime\") / ($__interval_ms * 2)) * 100) AS uptime_percentage\nFROM \"downtimes\"\nWHERE (\"app_name\"::tag = 'app3') OR (\"app_name\"::tag = 'app4') AND $timeFilter\nGROUP BY time($__interval) fill(100)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "app3 y app5",
     "query": "SELECT (100 - (sum(\"miliseconds_downtime\") / ($__interval_ms * 2)) * 100) AS uptime_percentage\nFROM \"downtimes\"\nWHERE (\"app_name\"::tag = 'app3') OR (\"app_name\"::tag = 'app5') AND $timeFilter\nGROUP BY time($__interval) fill(100)"
    }
   ]
  },
  {
   "title": "Valores de Uptime - App4 y App5",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "app4 y app5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (100 - (sum(\"miliseconds_downtime\") / ($__interval_ms * 2)) * 100) AS uptime_percentage\nFROM \"downtimes\"\nWHERE (\"app_name\"::tag = 'app4') OR (\"app_name\"::tag = 'app5') AND $timeFilter\nGROUP BY time($__interval) fill(100)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Downtimes Generales", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Valores de Downtime - Todas las apps",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 76 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downtimes",
     "query": "SELECT (sum(\"miliseconds_downtime\") / ($__interval_ms * 5)) * 100 AS uptime_percentage\nFROM \"downtimes\"\nWHERE  $timeFilter\nGROUP BY time($__interval), \"app_name\"::tag fill(100)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}